#!/bin/sh
# dhcp-on - start dhcp on a given interface
# Copyright (C) 2009 Peter Willis <peterwwillis@yahoo.com>
# 
# In some cases these defaults are more sane than dhcpcd's.
# For wireless interfaces and the general configuration of the system it's not
# always nice to overwrite default system settings every time you visit a new
# network. These settings assist that as well as make it easier to get an IP
# on an interface without worrying about the fine details.
# 

DHCPCD="/sbin/dhcpcd"
# Get some basic feedback from the app
DEBUG="-d"
# '-t 0':       Keep trying forever to get a lease, and if lease is lost, keep
#               trying forever to get a new one
TIMEOUT="-t 0"
# If dhcpcd is already running just try to renew the lease
TRY_TO_RENEW_LEASE="-n"
# Don't bring down interface if dhcpcd dies
DONT_BRING_DOWN_INTERFACE="-o"
# Don't bring down interface if dhcpcd dies AND leave ip address intact
#DONT_BRING_DOWN_INTERFACE_AND_KEEP_IP="-p"
# Default directory for dhcpcd's temporary/state files.
# If commented out defaults to /etc/dhcpc/INTERFACE/
#STATE_DIR="-L /etc/dhcpc"
# Run this script when dhcpcd configures or brings down an interface
IP_UPDOWN_SCRIPT="-c /etc/dhcpc/dhcpcd.exe"
# Where to create resolv.conf, ntp.conf and yp.conf.
# If commented out defaults to /etc/dhcpc/INTERFACE/
#ETC_DIR="/etc/dhcpc"

function dhcp_on_intf() {
    local intf="$1"
    local state="-L /etc/dhcpc/$intf"
    local etc="-e /etc/dhcpc/$intf"
    [ -n "$STATE_DIR" ] && state="$STATE_DIR"
    [ -n "$ETC_DIR" ] && etc="-e $ETC_DIR"
    echo "$0: $intf"
    echo "$0: $intf" | logger
    sudo $DHCPCD $intf $DEBUG $TIMEOUT $TRY_TO_RENEW_LEASE $DONT_BRING_DOWN_INTERFACE $DONT_BRING_DOWN_INTERFACE_AND_KEEP_IP $state $IP_UPDOWN_SCRIPT $etc &>/dev/null &
}

if [ "$1" = "-h" -o "$1" = "--help" ] ; then
  echo "Usage: $0 [INTERFACE ..]"
  echo "Starts dhcp on a given interface"
  exit 1
fi

if [ $# -lt 1 ] ; then
    for a in `ifconfig -a | grep encap:Ethernet | awk '{print $1}'` ; do
        dhcp_on_intf "$a"
    done
else
    for a in "$@" ; do
        dhcp_on_intf "$a"
    done
fi

